// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs6h_13LPtU8_XHAAn2LPQD9TwINCCx_k',
    appId: '1:709725167511:web:06d12a140709d4eb41aed2',
    messagingSenderId: '709725167511',
    projectId: 'social-media-app-f6108',
    authDomain: 'social-media-app-f6108.firebaseapp.com',
    storageBucket: 'social-media-app-f6108.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjDy1QAq0DwyymaEbSw-EieAHta7E9a3w',
    appId: '1:709725167511:android:425b3c633f262c9541aed2',
    messagingSenderId: '709725167511',
    projectId: 'social-media-app-f6108',
    storageBucket: 'social-media-app-f6108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP6nz-Cb9dIEy0jCq1j6FhkvpPz3grK6U',
    appId: '1:709725167511:ios:f86f39e4d802ad2241aed2',
    messagingSenderId: '709725167511',
    projectId: 'social-media-app-f6108',
    storageBucket: 'social-media-app-f6108.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP6nz-Cb9dIEy0jCq1j6FhkvpPz3grK6U',
    appId: '1:709725167511:ios:6e83c840c5555c7341aed2',
    messagingSenderId: '709725167511',
    projectId: 'social-media-app-f6108',
    storageBucket: 'social-media-app-f6108.appspot.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
